extern void input_Acursor_set(off_t c);
extern void input_Bcursor_set(off_t c);
extern off_t input_time_to_cursor(const char *t);
extern void input_cursor_to_time(off_t cursor,char *t);
extern void time_fix(char *buffer);
extern off_t input_seek(off_t pos);
extern time_linkage *input_read(void);
extern void input_parse(char *filename,int newgroup);
extern int input_load(void);
extern int pull_input_feedback(float *peak,float *rms,off_t *cursor);
extern void input_reset(void);
extern off_t input_time_seek_rel(float s);
